stages:
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gcr.io/imed-cl/rancher-demo:master-latest
      pushRemote: true
      registry: gcr.io
timeout: 60
notification: {}
